title:  Musings of Sumit Ghosh
author: Sumit Ghosh @SkullTech
email: sumit@sumit-ghosh.com
description: >
  My mind watching itself. 
timezone: Asia/Kolkata
url: https://sumit-ghosh.com
baseurl: ''

twitter_username: SkullTech101
github_username:  SkullTech
linkedin_username: sumit-ghosh101
instagram_username: summit.ghosh
flickr_username: sumit-ghosh

show_excerpts: false
minima:
  date_format: '%b %-d, %Y'

markdown: kramdown
theme: minima

include:
  - _pages
  
header_pages:
  - title: About
    url: '/about/'
  - title: Archive
    url: '/archive/'
  - title: Portfolio
    url: '/portfolio/'
  - title: Quotes
    url: '/quotes/'


exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

permalink: /articles/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled: ['tags']
  layout: tags
  permalinks:
    tag: '/archive/tag/:name/'

disqus:
    shortname: sumit-ghosh-com
google_analytics: UA-107859389-1
