title: Sumit's Dreams of Electric Sheeps
author: Sumit Ghosh
email: hi@sumit-ghosh.com
description: Blog on computers, programming, and everything in between.
timezone: Asia/Kolkata
url: https://sumit-ghosh.com
baseurl: ''

minima:
  social_links:
    twitter: summitkg
    linkedin: summitkg
    github: SkullTech

remote_theme: SkullTech/minima

include:
  - _redirects
  
header_pages:
  - archive.html

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

permalink: /articles/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag

jekyll-archives:
  enabled: ['tags', 'year']
  layout: archive
  permalinks:
    tag: '/archive/tag/:name/'
    year: '/archive/year/:year/'

disqus:
    shortname: sumit-ghosh-com
google_analytics: UA-107859389-1
