title:  Musings of Sumit Ghosh
author: Sumit Ghosh @SkullTech
email: sumit@sumit-ghosh.com
description: >  # this means to ignore newlines until another option
  Musings of a technologist. 
  My blog, double-serving as personal website.
# social links
twitter_username: SkullTech101
github_username:  SkullTech
rss: rss
linkedin_username: sumit-ghosh-skulltech

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Jekyll settings
include:
  - _pages

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

permalink: /articles/:title/
paginate: 5
