title:  Musings of Sumit Ghosh
author: Sumit Ghosh @SkullTech
email: sumit@sumit-ghosh.com
description: >
  My mind watching itself. 

twitter_username: SkullTech101
github_username:  SkullTech
linkedin_username: sumit-ghosh101
instagram_username: summit.ghosh

show_excerpts: false
minima:
  date_format: '%b %-d, %Y'

markdown: kramdown
theme: minima

include:
  - _pages

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

permalink: /articles/:title/
paginate: 5

plugins:
  - jekyll-feed

disqus:
    shortname: sumit-ghosh-com
google_analytics: UA-107859389-1
