title: Sumit's Space
author:
  name: Sumit Ghosh
  email: sumit@sumit-ghosh.com
description: Brain dump of things I find interesting.
timezone: Asia/Kolkata
url: https://sumit-ghosh.com
baseurl: ""

minima:
  social_links:
    - platform: twitter
      user_url: "https://twitter.com/summitkg"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/summitkg/"
    - platform: github
      user_url: "https://github.com/skulltech"
  skin: dark

remote_theme: jekyll/minima

include:
  - _redirects

exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - README.md
  - vendor

permalink: /posts/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

google_analytics: UA-107859389-1
